version: "3.4"
services:
    drupal:
        build:
            context: .
            dockerfile: ./docker/drupal/Dockerfile
            args:
                workdir: ${FRICKS_BASE_DIR}
        environment:
            FRICKS_BASE_DIR: ${FRICKS_BASE_DIR}
            FRICKS_BASE_URL: ${FRICKS_BASE_URL}
            FRICKS_DATABASE_HOST: ${FRICKS_DATABASE_HOST}
            FRICKS_DATABASE_PORT: ${FRICKS_DATABASE_PORT}
            FRICKS_DATABASE_NAME: ${FRICKS_DATABASE_NAME}
            FRICKS_DATABASE_USER: ${FRICKS_DATABASE_USER}
            FRICKS_DATABASE_PASSWORD: ${FRICKS_DATABASE_PASSWORD}
            FRICKS_DATABASE_DRIVER: ${FRICKS_DATABASE_DRIVER}
            FRICKS_CONFIG_UUID: ${FRICKS_CONFIG_UUID}
        volumes:
            - ./docker/drupal/php-conf.d/drupal.ini:/usr/local/etc/php/conf.d/drupal.ini:ro
            - ./drupal:${FRICKS_BASE_DIR}
            - ./front:${FRICKS_BASE_DIR}/../front

    database:
        image: mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: ${FRICKS_DATABASE_USER}
            MYSQL_PASSWORD: ${FRICKS_DATABASE_PASSWORD}
            MYSQL_DATABASE: ${FRICKS_DATABASE_NAME}
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_ROOT_HOST: '%'
        volumes:
            - drupal-db-data:/var/lib/mysql
            - ./docker/drupal/mysql-conf.d/drupal.cnf:/etc/mysql/conf.d/drupal.cnf:ro

    server:
        build:
            context: .
            dockerfile: ./docker/server/Dockerfile
        ports:
            - "80:80"
            - "443:443"
        environment:
            FRICKS_HOSTNAME: ${FRICKS_HOSTNAME}
            FRICKS_BASE_DIR: ${FRICKS_BASE_DIR}
        volumes:
            - ./docker/server/fricks.conf:/etc/nginx/conf.d/fricks.template:ro
            - ./docker/server/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./drupal:${FRICKS_BASE_DIR}
        command: /bin/bash -c "envsubst '$$FRICKS_BASE_DIR $$FRICKS_HOSTNAME' < /etc/nginx/conf.d/fricks.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

volumes:
    drupal-db-data: ~
